Repository GSG-G8/covid-19, pull requests merged in 2020-04, with the labels that each got.

#4 reademe file
  README.md
Labels: Done, awaiting-review

#6 2 file structre
  .gitignore
  README.md
  package.json
  public/index.html
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/components/App/App.css
  src/components/App/App.js
  src/index.css
  src/index.js
  yarn.lock
Labels: awaiting-review

#9 eslint configuration
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/components/App/App.js
Labels: awaiting-review

#12 create header and pages route
  package-lock.json
  package.json
  src/assets/images/logo.jpg
  src/components/App/App.js
  src/components/Header/Head.js
  src/components/Header/style.css
  src/pages/Awareness/Awareness.js
  src/pages/Awareness/style.css
  src/pages/Home/Home.js
  src/pages/Home/style.css
  src/pages/Information/Information.js
  src/pages/Information/style.css
Labels: awaiting-review

#17 create download spin
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Header/Head.js
  src/components/Header/style.css
  src/components/Spin/Spin.js
  src/components/Video/Empedvideo.js
  src/index.js
Labels: awaiting-review

#18 added card
  package.json
  src/components/card/index.css
  src/components/card/index.js
Labels: awaiting-review

#22 added search and autocomplete
  src/components/AutoComplete/index.css
  src/components/AutoComplete/index.js
Labels: awaiting-review

#23 Home Page | search by country
  src/components/Header/style.css
  src/components/Search/Search.js
  src/components/Search/style.css
  src/components/Spin/Spin.js
  src/components/Video/Empedvideo.js
  src/components/Video/style.css
  src/components/card/index.js
  src/pages/Home/Home.js
  src/pages/Home/style.css
Labels: awaiting-review

#28 27 change style nav information
  src/components/Header/Head.js
  src/components/Header/style.css
  src/pages/Awareness/Awareness.js
  src/pages/Information/style.css
Labels: Done
